# Generated by Django 3.0.7 on 2020-10-25 06:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('plasmid_database', '0004_plasmidfile_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('columns', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plasmid_database.Location')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('consumable', models.BooleanField(default=False)),
                ('consumed', models.BooleanField(default=False)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Container')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
