# Generated by Django 3.0.5 on 2020-06-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plasmid_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plasmid',
            name='assembly',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PlasmidAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plasmidinput', to='plasmid_database.Plasmid')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plasmidproduct', to='plasmid_database.Plasmid')),
            ],
            options={
                'unique_together': {('product', 'input')},
            },
        ),
    ]
