# Generated by Django 2.1.5 on 2019-02-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plasmid_database', '0003_auto_20190219_0143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plasmid',
            unique_together={('creator', 'creatorindex')},
        ),
    ]
