# Generated by Django 3.0.7 on 2020-06-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plasmid_database', '0002_auto_20200604_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmidFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('filename', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plasmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='plasmid_database.Plasmid')),
            ],
        ),
    ]
