# Generated by Django 3.0.7 on 2020-06-07 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plasmid_database', '0003_plasmidfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasmidfile',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
