# Generated by Django 3.0.7 on 2020-11-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20201102_0016'),
        ('plasmid_database', '0004_plasmidfile_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plasmid',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
