# Generated by Django 3.0.7 on 2021-05-19 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plasmid_database', '0005_auto_20201102_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmidPartPrimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlasmidPartFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('sequence', models.TextField()),
                ('method', models.TextField()),
                ('template', models.TextField()),
                ('plasmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plasmid_database.Plasmid')),
                ('primers', models.ManyToManyField(to='plasmid_database.PlasmidPartPrimer')),
            ],
        ),
    ]
