# Generated by Django 3.0.7 on 2021-05-20 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plasmid_database', '0006_plasmidpartfragment_plasmidpartprimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmidpartfragment',
            name='plasmid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='plasmid_database.Plasmid'),
        ),
    ]
