# Generated by Django 3.0.7 on 2021-05-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmid_database', '0009_plasmid_benchlingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmidpartprimer',
            name='sequence',
            field=models.TextField(unique=True),
        ),
    ]
